version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: ng01
        ports:
            - "8000:8000"
        volumes:
            - ./deploy/nginx:/etc/nginx/conf.d
        depends_on:
            - web
    web:
        build: .
        container_name: dg01
        volumes:
            - ./src:/src
            - ./deploy/uwsgi:/usr/local/etc/
        command: bash -c "sleep 5 && python /src/manage.py makemigrations && python /src/manage.py migrate && uwsgi --ini /usr/local/etc/elevennote.ini"
        depends_on:
            - db
        expose:
            - "8000"
    db:
        image: postgres:latest
        container_name: ps01
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
